language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install robotpy-rev==2020.1.04 
   
# command to run tests
script:
- py -3 /tests/drivetrain_test.py