language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -U pip
  - python3 -m pip install --no-use-pep517 robotpy_build 
  - python3 -m pip install --no-use-pep527 pyfrc
  - pip install robotpy-rev==2020.1.04 robotpy-rev-color
   
# command to run tests
script:
- py -3 /tests/drivetrain_test.py