deadzone = 0.2

#Motor IDs
LEFT_LEADER_ID = 8
LEFT_FOLLOWER_ID = 10
RIGHT_LEADER_ID = 7
RIGHT_FOLLOWER_ID = 9

COLOR_SENSOR_MOTOR = 2

CLIMBER_WINCH_MOTOR1 = 3 #TODO: Find actual port on robot
CLIMBER_WINCH_MOTOR2 = 5
#Soleoid IDs
COLOR_SENSOR_EXTEND = 5
COLOR_SENSOR_RETRACT = 4

CLIMBER_EXTEND =  2
CLIMBER_RETRACT = 3

DRIVE_SHIFT_EXTEND = 0
DRIVE_SHIFT_RETRACT = 1